language: rust
rust: nightly

sudo: required

# Cache cargo symbols for faster build
cache: cargo

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-update || echo "cargo-update already installed"
  - cargo install-update -a # update outdated cached binaries

# the main build
script:
  - |
      cargo build
      cargo test

notifications:
  email: false

branches:
  only: master
